openapi: 3.0.3
info:
  version: 1.0.0
  title: Empleo API
  description: Empleo api 
  x-sla:
    $ref: ./plans.yaml
security:
  - BearerAuth: []
paths:
  /api/v1/empleo:
    x-router-controller: empleoController
    get:
      description: Returns all empleo
      operationId: getEmpleo
      responses:
        200:
          description: Empleo list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/empleo'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    
                  
  /api/v1/empleo/{id}:
    x-router-controller: empleoController
    get:
      description: Returns a single team by its id
      operationId: findByid
      parameters:
        - required: true
          name: id
          description: id of the empleo to fetch
          in: path
          schema:
            type: number
      responses:
        200:
          description: Empleo found by id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/empleo'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    
    

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    empleo:
        type: object
        required:
          - id
        properties:
          id:
            type: number
          name:
            type: string
          code:
            type: string
          country:
            type: string
          founded:
            type: number
          national:
            type: boolean
          logo:
            type: string
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
      additionalProperties: true